05. BlogWebsite/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BlogWebsite.Models
{
    public class Post
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Gde title?")]
        [MaxLength(100)]
        [Display(Name = "Post title")]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime Date { get; set; }

        [Display(Name = "Post main image")]
        [DataType(DataType.Upload)]
        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }

        public Category Category { get; set; }

        public IEnumerable<PostTag> PostTags { get; set; }
    }
}

05. BlogWebsite/Controllers/PostController.cs
using BlogWebsite.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogWebsite.Controllers
{
    public class PostController : Controller
    {
        private readonly BlogDbContext context;

        public PostController(BlogDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(context.Posts);
        }

        [HttpGet]
        public IActionResult Add()
        {
            //ModelState.AddModelError("Title", "Error!!!!");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Post post)
        {
            if (ModelState.IsValid)
            {
                post.Date = DateTime.Now;
                context.Posts.Add(post);
                await context.SaveChangesAsync();
                TempData["Status"] = "New post added!";
                return RedirectToAction("Index");
            }
            return View(post);
        }
    }
}

05. BlogWebsite/Controllers/PostsController.cs
using BlogWebsite.Helpers;
using BlogWebsite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogWebsite.Extensions;

namespace BlogWebsite.Controllers
{
    public class PostsController : Controller
    {
        private readonly BlogDbContext context;

        public PostsController(BlogDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(context.Posts);
        }

        [HttpGet]
        public IActionResult Add()
        {
            //ModelState.AddModelError("Title", "Error!!!!");
            ViewBag.Categories = new SelectList(context.Categories, "Id", "Name");
            ViewBag.Tags = new MultiSelectList(context.Tags, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Post post, IFormFile Image, int[] tags)
        {
            var path = await FileUploadHelper.UploadAsync(Image);
            post.ImageUrl = path;

            if (ModelState.IsValid)
            {
                post.Date = DateTime.Now;
                context.Posts.Add(post);
                await context.SaveChangesAsync();

                //foreach (var item in tags)
                //{
                //    context.PostTags.Add(new PostTag { TagId = item, PostId = post.Id });
                //}

                //[1, 3, 5] => [{ PostId = 25, TagId = 1 }, { PostId = 25, TagId = 3 }, { PostId = 25, TagId = 5 }]
                context.PostTags.AddRange(tags.Select(x => new PostTag { PostId = post.Id, TagId = x }));
                await context.SaveChangesAsync();

                TempData["Status"] = "New post added!";
                return RedirectToAction("Index");
            }
            return View(post);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var post = context.Posts.Find(id);
            ViewBag.Categories = new SelectList(context.Categories, "Id", "Name");
            var selectedTagsIds = context.PostTags.Where(x => x.PostId == id).Select(x => x.TagId);
            ViewBag.Tags = new MultiSelectList(context.Tags, "Id", "Name", selectedTagsIds);
            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post post, IFormFile Image, int[] tags)
        {
            if (Image != null)
            {
                var path = await FileUploadHelper.UploadAsync(Image);
                post.ImageUrl = path;
            }
            post.Date = DateTime.Now;
            context.Posts.Update(post);
            await context.SaveChangesAsync();
          
            context.UpdateManyToMany(
                context.PostTags.Where(x => x.PostId == post.Id),
                tags.Select(x => new PostTag { PostId = post.Id, TagId = x }),
                x => x.TagId);

            await context.SaveChangesAsync();

            TempData["Status"] = "Post edited!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var post = context.Posts
                .Include(x => x.PostTags)
                .ThenInclude(x => x.Tag)
                .Include(x => x.Category)
                .FirstOrDefault(x => x.Id == id);
            return View(post);
        }

        
    }
}

05. BlogWebsite/Views/Post/Add.cshtml
@model Post
@{
    ViewData["Title"] = "AddPost";
}

<h1>AddPost</h1>

<form asp-controller="Post" asp-action="Add" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" class="form-control"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <button class="btn btn-primary">Add</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

@*<form asp-controller="Post" asp-action="Add" method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input name="Title" type="text" class="form-control" id="title" placeholder="Title">
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input name="ImageUrl" type="text" class="form-control" id="ImageUrl" placeholder="ImageUrl">
    </div>
    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="Content" class="form-control" id="content" rows="3"></textarea>
    </div>
    <button class="btn btn-primary">Add</button>
</form>*@

05. BlogWebsite/Views/Post/Index.cshtml
@model IEnumerable<Post>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@if (TempData.ContainsKey("Status"))
{
<div class="alert alert-success alert-dismissible fade show" role="alert">
    @TempData["Status"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
}

<div class="list-group">

    @foreach (var item in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">@item.Title</h5>
                <small>@item.Date</small>
            </div>
            <p class="mb-1">@item.Content</p>
        </a>
    }
</div>

<a asp-controller="Post" asp-action="Add">Add new post</a>